# Generated by Django 5.2.4 on 2025-07-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
